name: evn_pro
description: EVN Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
